
version: '3.6'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://user:pass@db/twitter
    networks:
      - default
    ports:
      - 5050:5050
    volumes:
      - ./:/usr/src/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  db:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: twitter
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always