"""empty message

Revision ID: 783d47b912ae
Revises: 
Create Date: 2023-05-28 11:39:05.135849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783d47b912ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
